---

name: Devel

on:
  push:
    branches: [devel]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Push devel image
    steps:
      - uses: actions/checkout@v4

      - name: Fail if QUAY_REGISTRY not set
        run: |
          if [[ -z "${{ vars.QUAY_REGISTRY }}" ]]; then
            echo "QUAY_REGISTRY not set. Please set QUAY_REGISTRY in variable GitHub Actions variables."
            exit 1
          fi

      - name: Log into registry ghcr.io
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772    # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Log into registry quay.io
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772    # v3.4.0
        with:
          registry: ${{ vars.QUAY_REGISTRY }}
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}


      - name: Build and Store Image @ghcr
        run: |
          IMG=ghcr.io/${{ github.repository }}:${{ github.sha }} make docker-buildx


      - name: Publish Image to quay.io
        run: |
          docker buildx imagetools create \
            ghcr.io/${{ github.repository }}:${{ github.sha }} \
            --tag ${{ vars.QUAY_REGISTRY }}/awx-operator:devel
